import SwiftUI

// Generated by Supernova - do not modify manually
public struct AppMeasures {

    // Dimension

    // fonts

    // Space

    // spacing
    public static let spacespacing0 = 0 
    public static let spacespacingPx = 1 
    public static let spacespacing05 = 2 
    public static let spacespacing1 = 4 
    public static let spacespacing2 = 8 
    public static let spacespacing3 = 12 
    public static let spacespacing4 = 16 
    public static let spacespacing5 = 20 
    public static let spacespacing6 = 24 
    public static let spacespacing7 = 28 
    public static let spacespacing8 = 32 
    public static let spacespacing16 = 64 
    public static let spacespacing52 = 208 

    // Font Size

    // fonts

    // font size
    public static let fontSizefontsfontSizeXs = 12 
    public static let fontSizefontsfontSizeSm = 14 
    public static let fontSizefontsfontSizeBase = 16 
    public static let fontSizefontsfontSizeLg = 18 
    public static let fontSizefontsfontSizeXl = 20 
    public static let fontSizefontsfontSize2Xl = 24 
    public static let fontSizefontsfontSize3Xl = 30 
    public static let fontSizefontsfontSize4Xl = 36 
    public static let fontSizefontsfontSize5Xl = 48 
    public static let fontSizefontsfontSize6Xl = 60 
    public static let fontSizefontsfontSize7Xl = 72 
    public static let fontSizefontsfontSize8Xl = 96 
    public static let fontSizefontsfontSize9Xl = 128 

    // Line Height

    // fonts

    // line height
    public static let lineHeightfontslineHeight16 = 16 
    public static let lineHeightfontslineHeight20 = 20 
    public static let lineHeightfontslineHeight24 = 24 
    public static let lineHeightfontslineHeight28 = 28 
    public static let lineHeightfontslineHeight32 = 32 
    public static let lineHeightfontslineHeight36 = 36 
    public static let lineHeightfontslineHeight40 = 40 
    public static let lineHeightfontslineHeight48 = 48 
    public static let lineHeightfontslineHeight60 = 60 
    public static let lineHeightfontslineHeight64 = 64 
    public static let lineHeightfontslineHeight72 = 72 

    // Border Width

    // border width
    public static let borderWidthborderWidthBorder1 = 1 
    public static let borderWidthborderWidthBorder2 = 2 

    // Border Radius

    // border radius
    public static let borderRadiusborderRadiusRounded = 4 
    public static let borderRadiusborderRadiusRoundedMd = 6 
    public static let borderRadiusborderRadiusRoundedLg = 8 
    public static let borderRadiusborderRadiusRoundedXl = 12 
}