import SwiftUI

// Generated by Supernova - do not modify manually
public extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        // color
        public let colorWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let colorBlack = Color(.sRGB, red: 28/255, green: 28/255, blue: 28/255, opacity: 1) 

        // navy
        public let colornavy100 = Color(.sRGB, red: 217/255, green: 221/255, blue: 224/255, opacity: 1) 
        public let colornavy200 = Color(.sRGB, red: 180/255, green: 187/255, blue: 194/255, opacity: 1) 
        public let colornavy300 = Color(.sRGB, red: 142/255, green: 154/255, blue: 164/255, opacity: 1) 
        public let colornavy400 = Color(.sRGB, red: 30/255, green: 53/255, blue: 74/255, opacity: 1) 
        public let colornavy500 = Color(.sRGB, red: 25/255, green: 44/255, blue: 61/255, opacity: 1) 
        public let colornavy600 = Color(.sRGB, red: 15/255, green: 26/255, blue: 37/255, opacity: 1) 

        // blue
        public let colorblue100 = Color(.sRGB, red: 236/255, green: 248/255, blue: 255/255, opacity: 1) 
        public let colorblue200 = Color(.sRGB, red: 170/255, green: 222/255, blue: 255/255, opacity: 1) 
        public let colorblue300 = Color(.sRGB, red: 127/255, green: 205/255, blue: 255/255, opacity: 1) 
        public let colorblue400 = Color(.sRGB, red: 0/255, green: 156/255, blue: 255/255, opacity: 1) 
        public let colorblue500 = Color(.sRGB, red: 0/255, green: 130/255, blue: 212/255, opacity: 1) 
        public let colorblue600 = Color(.sRGB, red: 0/255, green: 94/255, blue: 154/255, opacity: 1) 

        // gold
        public let colorgold100 = Color(.sRGB, red: 249/255, green: 245/255, blue: 235/255, opacity: 1) 
        public let colorgold200 = Color(.sRGB, red: 197/255, green: 151/255, blue: 51/255, opacity: 1) 
        public let colorgold300 = Color(.sRGB, red: 98/255, green: 75/255, blue: 25/255, opacity: 1) 

        // grey
        public let colorgrey100 = Color(.sRGB, red: 240/255, green: 242/255, blue: 245/255, opacity: 1) 
        public let colorgrey200 = Color(.sRGB, red: 208/255, green: 213/255, blue: 221/255, opacity: 1) 
        public let colorgrey300 = Color(.sRGB, red: 102/255, green: 112/255, blue: 133/255, opacity: 1) 
        public let colorgrey400 = Color(.sRGB, red: 52/255, green: 64/255, blue: 84/255, opacity: 1) 

        // green
        public let colorgreen100 = Color(.sRGB, red: 241/255, green: 249/255, blue: 241/255, opacity: 1) 
        public let colorgreen200 = Color(.sRGB, red: 225/255, green: 241/255, blue: 225/255, opacity: 1) 
        public let colorgreen300 = Color(.sRGB, red: 76/255, green: 175/255, blue: 80/255, opacity: 1) 
        public let colorgreen400 = Color(.sRGB, red: 50/255, green: 116/255, blue: 53/255, opacity: 1) 

        // orange
        public let colororange100 = Color(.sRGB, red: 255/255, green: 248/255, blue: 240/255, opacity: 1) 
        public let colororange200 = Color(.sRGB, red: 254/255, green: 237/255, blue: 218/255, opacity: 1) 
        public let colororange300 = Color(.sRGB, red: 253/255, green: 151/255, blue: 38/255, opacity: 1) 
        public let colororange400 = Color(.sRGB, red: 168/255, green: 100/255, blue: 25/255, opacity: 1) 

        // red
        public let colorred100 = Color(.sRGB, red: 253/255, green: 241/255, blue: 241/255, opacity: 1) 
        public let colorred200 = Color(.sRGB, red: 249/255, green: 221/255, blue: 220/255, opacity: 1) 
        public let colorred300 = Color(.sRGB, red: 220/255, green: 54/255, blue: 46/255, opacity: 1) 
        public let colorred400 = Color(.sRGB, red: 180/255, green: 35/255, blue: 24/255, opacity: 1) 
        public let colorred500 = Color(.sRGB, red: 145/255, green: 32/255, blue: 24/255, opacity: 1) 

        // accent
        public let coloraccentJfxgoldx = Color(.sRGB, red: 13/255, green: 29/255, blue: 44/255, opacity: 1) 
        public let coloraccentBmtdigi = Color(.sRGB, red: 111/255, green: 19/255, blue: 45/255, opacity: 1) 
        public let coloraccentMetalgo = Color(.sRGB, red: 0/255, green: 156/255, blue: 255/255, opacity: 1) 
        public let coloraccentPospaygold = Color(.sRGB, red: 241/255, green: 106/255, blue: 34/255, opacity: 1) 
        public let coloraccentNunomics = Color(.sRGB, red: 0/255, green: 84/255, blue: 26/255, opacity: 1) 
        public let coloraccentAgigold = Color(.sRGB, red: 14/255, green: 186/255, blue: 192/255, opacity: 1) 

        // core
        public let colorcoreWhite = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let colorcoreBlack = Color(.sRGB, red: 28/255, green: 28/255, blue: 28/255, opacity: 1) 

        // background
        public let colorbackgroundBackgroundPrimary = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let colorbackgroundBackgroundSecondary = Color(.sRGB, red: 240/255, green: 242/255, blue: 245/255, opacity: 1) 
        public let colorbackgroundBackgroundTertiary = Color(.sRGB, red: 30/255, green: 53/255, blue: 74/255, opacity: 1) 
        public let colorbackgroundBackgroundInverseTertiary = Color(.sRGB, red: 217/255, green: 221/255, blue: 224/255, opacity: 1) 

        // extensions
        public let colorbackgroundextensionsBackgroundRed = Color(.sRGB, red: 253/255, green: 241/255, blue: 241/255, opacity: 1) 
        public let colorbackgroundextensionsBackgroundOrange = Color(.sRGB, red: 255/255, green: 248/255, blue: 240/255, opacity: 1) 
        public let colorbackgroundextensionsBackgroundBlue = Color(.sRGB, red: 236/255, green: 248/255, blue: 255/255, opacity: 1) 
        public let colorbackgroundextensionsBackgroundGreen = Color(.sRGB, red: 241/255, green: 249/255, blue: 241/255, opacity: 1) 
        public let colorbackgroundextensionsBackgroundGold = Color(.sRGB, red: 249/255, green: 245/255, blue: 235/255, opacity: 1) 

        // content
        public let colorcontentContentPrimary = Color(.sRGB, red: 28/255, green: 28/255, blue: 28/255, opacity: 1) 
        public let colorcontentContentSecondary = Color(.sRGB, red: 30/255, green: 53/255, blue: 74/255, opacity: 1) 
        public let colorcontentContentTertiary = Color(.sRGB, red: 102/255, green: 112/255, blue: 133/255, opacity: 1) 
        public let colorcontentContentInversePrimary = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        public let colorcontentContentInverseSecondary = Color(.sRGB, red: 142/255, green: 154/255, blue: 164/255, opacity: 1) 

        // extensions
        public let colorcontentextensionsContentRed = Color(.sRGB, red: 220/255, green: 54/255, blue: 46/255, opacity: 1) 
        public let colorcontentextensionsContentOrange = Color(.sRGB, red: 253/255, green: 151/255, blue: 38/255, opacity: 1) 
        public let colorcontentextensionsContentGreen = Color(.sRGB, red: 50/255, green: 116/255, blue: 53/255, opacity: 1) 
        public let colorcontentextensionsContentBlue = Color(.sRGB, red: 0/255, green: 156/255, blue: 255/255, opacity: 1) 
        public let colorcontentextensionsContentGold = Color(.sRGB, red: 98/255, green: 75/255, blue: 25/255, opacity: 1) 

        // border
        public let colorborderBorderPrimary = Color(.sRGB, red: 208/255, green: 213/255, blue: 221/255, opacity: 1) 
        public let colorborderBorderSecondary = Color(.sRGB, red: 240/255, green: 242/255, blue: 245/255, opacity: 1) 
        public let colorborderBorderTertiary = Color(.sRGB, red: 30/255, green: 53/255, blue: 74/255, opacity: 1) 

        // extensions
        public let colorborderextensionsBorderInfo = Color(.sRGB, red: 0/255, green: 156/255, blue: 255/255, opacity: 1) 
        public let colorborderextensionsBorderSuccess = Color(.sRGB, red: 76/255, green: 175/255, blue: 80/255, opacity: 1) 
        public let colorborderextensionsBorderError = Color(.sRGB, red: 220/255, green: 54/255, blue: 46/255, opacity: 1) 
    }
}